core:
    resource: "@AppBundle/Controller/CoreController.php"
    type:     annotation
    prefix:   /
app:
    resource: "@AppBundle/Controller/AjaxController.php"
    type:     annotation
    prefix:   /ajax
App:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /



