core:
    resource: "@AppBundle/Controller/CoreController.php"
    type:     annotation
    prefix:   /

App:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /



