# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUDO_ADMIN: [ROLE_USER, ROLE_ADMIN]

    providers:
        main_provider:
            entity:
                class:    UserBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            provider: main_provider
            form_login:
                login_path: /connexion
                check_path: /verif_connexion
            logout:
                path: /deconnexion
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(observation|profil), roles: ROLE_USER }
